version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "go"
    labels:
      - "dependencies"
      - "go"
    versioning-strategy: increase

  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "docs"
    labels:
      - "dependencies"
      - "docs"
    versioning-strategy: increase